# Declara o estado desejado da aplicação 'landing-page' no Kubernetes, especificando a imagem a ser usada e o número de réplicas (pods).

apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: acrdevlab001eastus.azurecr.io/cursoia-land:latest
          ports:
            - containerPort: 80
