# Define como expor os pods da aplicação 'landing-page' na rede, atribuindo-lhes um IP acessível (LoadBalancer público)

apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  type: LoadBalancer
  selector:
    app: landing-page
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
